/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteRouteImport } from './routes/_chat/route'
import { Route as DevIconsRouteImport } from './routes/dev.icons'
import { Route as ChatSettingsRouteRouteImport } from './routes/_chat/settings/route'
import { Route as ChatShellRouteRouteImport } from './routes/_chat/_shell/route'
import { Route as ChatShellIndexRouteImport } from './routes/_chat/_shell/index'
import { Route as ChatSettingsExtensionsRouteImport } from './routes/_chat/settings/extensions'
import { Route as ChatSettingsArchivedRouteImport } from './routes/_chat/settings/archived'
import { Route as ChatSettingsAppearanceRouteImport } from './routes/_chat/settings/appearance'
import { Route as ChatSettingsAgentsRouteImport } from './routes/_chat/settings/agents'
import { Route as ChatShellThreadIdRouteImport } from './routes/_chat/_shell/$threadId'

const ChatRouteRoute = ChatRouteRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DevIconsRoute = DevIconsRouteImport.update({
  id: '/dev/icons',
  path: '/dev/icons',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatSettingsRouteRoute = ChatSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ChatRouteRoute,
} as any)
const ChatShellRouteRoute = ChatShellRouteRouteImport.update({
  id: '/_shell',
  getParentRoute: () => ChatRouteRoute,
} as any)
const ChatShellIndexRoute = ChatShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatShellRouteRoute,
} as any)
const ChatSettingsExtensionsRoute = ChatSettingsExtensionsRouteImport.update({
  id: '/extensions',
  path: '/extensions',
  getParentRoute: () => ChatSettingsRouteRoute,
} as any)
const ChatSettingsArchivedRoute = ChatSettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => ChatSettingsRouteRoute,
} as any)
const ChatSettingsAppearanceRoute = ChatSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => ChatSettingsRouteRoute,
} as any)
const ChatSettingsAgentsRoute = ChatSettingsAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => ChatSettingsRouteRoute,
} as any)
const ChatShellThreadIdRoute = ChatShellThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatShellRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatShellIndexRoute
  '/settings': typeof ChatSettingsRouteRouteWithChildren
  '/dev/icons': typeof DevIconsRoute
  '/$threadId': typeof ChatShellThreadIdRoute
  '/settings/agents': typeof ChatSettingsAgentsRoute
  '/settings/appearance': typeof ChatSettingsAppearanceRoute
  '/settings/archived': typeof ChatSettingsArchivedRoute
  '/settings/extensions': typeof ChatSettingsExtensionsRoute
}
export interface FileRoutesByTo {
  '/': typeof ChatShellIndexRoute
  '/settings': typeof ChatSettingsRouteRouteWithChildren
  '/dev/icons': typeof DevIconsRoute
  '/$threadId': typeof ChatShellThreadIdRoute
  '/settings/agents': typeof ChatSettingsAgentsRoute
  '/settings/appearance': typeof ChatSettingsAppearanceRoute
  '/settings/archived': typeof ChatSettingsArchivedRoute
  '/settings/extensions': typeof ChatSettingsExtensionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteRouteWithChildren
  '/_chat/_shell': typeof ChatShellRouteRouteWithChildren
  '/_chat/settings': typeof ChatSettingsRouteRouteWithChildren
  '/dev/icons': typeof DevIconsRoute
  '/_chat/_shell/$threadId': typeof ChatShellThreadIdRoute
  '/_chat/settings/agents': typeof ChatSettingsAgentsRoute
  '/_chat/settings/appearance': typeof ChatSettingsAppearanceRoute
  '/_chat/settings/archived': typeof ChatSettingsArchivedRoute
  '/_chat/settings/extensions': typeof ChatSettingsExtensionsRoute
  '/_chat/_shell/': typeof ChatShellIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/dev/icons'
    | '/$threadId'
    | '/settings/agents'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/extensions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/dev/icons'
    | '/$threadId'
    | '/settings/agents'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/extensions'
  id:
    | '__root__'
    | '/_chat'
    | '/_chat/_shell'
    | '/_chat/settings'
    | '/dev/icons'
    | '/_chat/_shell/$threadId'
    | '/_chat/settings/agents'
    | '/_chat/settings/appearance'
    | '/_chat/settings/archived'
    | '/_chat/settings/extensions'
    | '/_chat/_shell/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRouteRoute: typeof ChatRouteRouteWithChildren
  DevIconsRoute: typeof DevIconsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/icons': {
      id: '/dev/icons'
      path: '/dev/icons'
      fullPath: '/dev/icons'
      preLoaderRoute: typeof DevIconsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/settings': {
      id: '/_chat/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ChatSettingsRouteRouteImport
      parentRoute: typeof ChatRouteRoute
    }
    '/_chat/_shell': {
      id: '/_chat/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatShellRouteRouteImport
      parentRoute: typeof ChatRouteRoute
    }
    '/_chat/_shell/': {
      id: '/_chat/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatShellIndexRouteImport
      parentRoute: typeof ChatShellRouteRoute
    }
    '/_chat/settings/extensions': {
      id: '/_chat/settings/extensions'
      path: '/extensions'
      fullPath: '/settings/extensions'
      preLoaderRoute: typeof ChatSettingsExtensionsRouteImport
      parentRoute: typeof ChatSettingsRouteRoute
    }
    '/_chat/settings/archived': {
      id: '/_chat/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof ChatSettingsArchivedRouteImport
      parentRoute: typeof ChatSettingsRouteRoute
    }
    '/_chat/settings/appearance': {
      id: '/_chat/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof ChatSettingsAppearanceRouteImport
      parentRoute: typeof ChatSettingsRouteRoute
    }
    '/_chat/settings/agents': {
      id: '/_chat/settings/agents'
      path: '/agents'
      fullPath: '/settings/agents'
      preLoaderRoute: typeof ChatSettingsAgentsRouteImport
      parentRoute: typeof ChatSettingsRouteRoute
    }
    '/_chat/_shell/$threadId': {
      id: '/_chat/_shell/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ChatShellThreadIdRouteImport
      parentRoute: typeof ChatShellRouteRoute
    }
  }
}

interface ChatShellRouteRouteChildren {
  ChatShellThreadIdRoute: typeof ChatShellThreadIdRoute
  ChatShellIndexRoute: typeof ChatShellIndexRoute
}

const ChatShellRouteRouteChildren: ChatShellRouteRouteChildren = {
  ChatShellThreadIdRoute: ChatShellThreadIdRoute,
  ChatShellIndexRoute: ChatShellIndexRoute,
}

const ChatShellRouteRouteWithChildren = ChatShellRouteRoute._addFileChildren(
  ChatShellRouteRouteChildren,
)

interface ChatSettingsRouteRouteChildren {
  ChatSettingsAgentsRoute: typeof ChatSettingsAgentsRoute
  ChatSettingsAppearanceRoute: typeof ChatSettingsAppearanceRoute
  ChatSettingsArchivedRoute: typeof ChatSettingsArchivedRoute
  ChatSettingsExtensionsRoute: typeof ChatSettingsExtensionsRoute
}

const ChatSettingsRouteRouteChildren: ChatSettingsRouteRouteChildren = {
  ChatSettingsAgentsRoute: ChatSettingsAgentsRoute,
  ChatSettingsAppearanceRoute: ChatSettingsAppearanceRoute,
  ChatSettingsArchivedRoute: ChatSettingsArchivedRoute,
  ChatSettingsExtensionsRoute: ChatSettingsExtensionsRoute,
}

const ChatSettingsRouteRouteWithChildren =
  ChatSettingsRouteRoute._addFileChildren(ChatSettingsRouteRouteChildren)

interface ChatRouteRouteChildren {
  ChatShellRouteRoute: typeof ChatShellRouteRouteWithChildren
  ChatSettingsRouteRoute: typeof ChatSettingsRouteRouteWithChildren
}

const ChatRouteRouteChildren: ChatRouteRouteChildren = {
  ChatShellRouteRoute: ChatShellRouteRouteWithChildren,
  ChatSettingsRouteRoute: ChatSettingsRouteRouteWithChildren,
}

const ChatRouteRouteWithChildren = ChatRouteRoute._addFileChildren(
  ChatRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRouteRoute: ChatRouteRouteWithChildren,
  DevIconsRoute: DevIconsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
