import type { ComponentType, SVGProps } from "react";
import {
  IconAgent,
  IconAppearanceLightMode,
  IconArchive,
  IconArrowCornerDownRight,
  IconArrowLeft,
  IconArrowOutOfBox,
  IconArrowRotateClockwise,
  IconArrowRotateCounterClockwise,
  IconArrowUp,
  IconBolt,
  IconBrain,
  IconCheckmark1Small,
  IconChevronBottom,
  IconChevronDownSmall,
  IconChevronLeft,
  IconChevronRight,
  IconCircleCheck,
  IconClipboard,
  IconCloudDownload,
  IconConsole,
  IconCrossSmall,
  IconFileBend,
  IconFolder1,
  IconFolderOpen,
  IconImages1,
  IconLightning,
  IconLoader,
  IconPlusLarge,
  IconPuzzle,
  IconSearchIntelligence,
  IconSettingsGear2,
  IconSidebar,
  IconSidebarHiddenLeftWide,
  IconSidebarHiddenRightWide,
  IconBuildingBlocks,
  IconStop,
  IconToolbox,
  IconX,
} from "central-icons";

export type GlassCentralIconEntry = {
  name: string;
  Cmp: ComponentType<SVGProps<SVGSVGElement>>;
  usage: string;
};

/** Canonical list of `central-icons` components used by the Glass UI (Electron loads this web bundle). */
export const glassCentralIcons: GlassCentralIconEntry[] = [
  { name: "IconAgent", Cmp: IconAgent, usage: "Settings: Agents" },
  { name: "IconAppearanceLightMode", Cmp: IconAppearanceLightMode, usage: "Settings: Appearance" },
  { name: "IconArchive", Cmp: IconArchive, usage: "Settings: Archived" },
  {
    name: "IconArrowCornerDownRight",
    Cmp: IconArrowCornerDownRight,
    usage: "Diff sidebar: nested file",
  },
  { name: "IconArrowLeft", Cmp: IconArrowLeft, usage: "App shell: back" },
  { name: "IconArrowOutOfBox", Cmp: IconArrowOutOfBox, usage: "Open picker: external" },
  {
    name: "IconArrowRotateClockwise",
    Cmp: IconArrowRotateClockwise,
    usage: "Update pill: refresh",
  },
  {
    name: "IconArrowRotateCounterClockwise",
    Cmp: IconArrowRotateCounterClockwise,
    usage: "Git panel, settings: discard / reset",
  },
  { name: "IconArrowUp", Cmp: IconArrowUp, usage: "Composer: send" },
  { name: "IconBolt", Cmp: IconBolt, usage: "Slash menu: subagent" },
  { name: "IconBrain", Cmp: IconBrain, usage: "Model picker" },
  {
    name: "IconCheckmark1Small",
    Cmp: IconCheckmark1Small,
    usage: "Selections, combobox, open picker",
  },
  { name: "IconChevronBottom", Cmp: IconChevronBottom, usage: "Expand, combobox, chat rows" },
  { name: "IconChevronDownSmall", Cmp: IconChevronDownSmall, usage: "Git panel, open picker" },
  { name: "IconChevronLeft", Cmp: IconChevronLeft, usage: "Ask tool: prev" },
  { name: "IconChevronRight", Cmp: IconChevronRight, usage: "Menus, git, model picker" },
  { name: "IconCircleCheck", Cmp: IconCircleCheck, usage: "Sonner: success" },
  { name: "IconClipboard", Cmp: IconClipboard, usage: "Chat rows: copy" },
  { name: "IconCloudDownload", Cmp: IconCloudDownload, usage: "Update pill: download" },
  { name: "IconConsole", Cmp: IconConsole, usage: "Chat rows: terminal attachment" },
  { name: "IconCrossSmall", Cmp: IconCrossSmall, usage: "Close, destructive, dialogs, composer" },
  { name: "IconFileBend", Cmp: IconFileBend, usage: "Files, git, slash, fallback file icon" },
  { name: "IconFolder1", Cmp: IconFolder1, usage: "Workspace picker, slash: folder" },
  { name: "IconFolderOpen", Cmp: IconFolderOpen, usage: "Open picker: open folder" },
  { name: "IconImages1", Cmp: IconImages1, usage: "Composer / chat: image" },
  { name: "IconLightning", Cmp: IconLightning, usage: "Slash menu: commands" },
  { name: "IconLoader", Cmp: IconLoader, usage: "Loading rows, Sonner" },
  {
    name: "IconPlusLarge",
    Cmp: IconPlusLarge,
    usage: "Sidebar header, composer attach, command palette",
  },
  { name: "IconPuzzle", Cmp: IconPuzzle, usage: "Settings: Extensions" },
  { name: "IconSearchIntelligence", Cmp: IconSearchIntelligence, usage: "Composer file preview" },
  {
    name: "IconSettingsGear2",
    Cmp: IconSettingsGear2,
    usage: "Footer, slash app, command palette",
  },
  { name: "IconSidebar", Cmp: IconSidebar, usage: "Sidebar toggle (visible)" },
  {
    name: "IconSidebarHiddenLeftWide",
    Cmp: IconSidebarHiddenLeftWide,
    usage: "Sidebar hidden (left)",
  },
  {
    name: "IconSidebarHiddenRightWide",
    Cmp: IconSidebarHiddenRightWide,
    usage: "Composer sidebar hidden",
  },
  { name: "IconBuildingBlocks", Cmp: IconBuildingBlocks, usage: "Slash menu: skills" },
  { name: "IconStop", Cmp: IconStop, usage: "Composer: stop" },
  { name: "IconToolbox", Cmp: IconToolbox, usage: "Chat rows: tools" },
  { name: "IconX", Cmp: IconX, usage: "Sheet, combobox clear" },
];
