/** Semantic shell maps derived from @pierre/theme VS Code themes (sideBar, editor, list, git). */
/* Intentionally omit --background, --card, --popover: avoid full-bleed page/top-bar tint; shell header stays transparent. */

export const PIERRE_DARK_VARS: Record<string, string> = {
  "--foreground": "#fbfbfb",
  "--primary": "#009fff",
  "--primary-foreground": "#070707",
  "--secondary": "color-mix(in srgb, #fbfbfb 8%, #070707)",
  "--secondary-foreground": "#fbfbfb",
  "--muted": "color-mix(in srgb, #fbfbfb 6%, #070707)",
  "--muted-foreground": "#84848a",
  "--accent": "#19283c73",
  "--accent-foreground": "#fbfbfb",
  "--destructive": "#ff2e3f",
  "--border": "#1f1f21",
  "--input": "#1f1f21",
  "--ring": "oklch(0.68 0.14 245 / 45%)",
  "--glass-color-sidebar": "#141415",
  "--glass-color-chat": "#0a0a0a",
  "--glass-color-editor": "#070707",
  "--glass-color-surface": "#0c0c0c",
  "--glass-color-elevated": "#141415",
  "--glass-color-bubble": "color-mix(in srgb, #141415 88%, transparent)",
  "--glass-color-bubble-opaque": "#141415",
  "--glass-color-menubar": "color-mix(in srgb, #070707 80%, #141415)",
  "--glass-color-border": "color-mix(in srgb, #fbfbfb 10%, transparent)",
  "--glass-color-stroke": "color-mix(in srgb, #fbfbfb 8%, transparent)",
  "--glass-color-stroke-tertiary": "color-mix(in srgb, #fbfbfb 6%, transparent)",
  "--glass-color-stroke-strong": "color-mix(in srgb, #fbfbfb 14%, transparent)",
  "--glass-color-hover": "#19283c59",
  "--glass-color-active": "#19283c99",
  "--glass-diff-addition": "#00cab1",
  "--glass-diff-deletion": "#ff2e3f",
  "--glass-diff-addition-bg": "color-mix(in srgb, #00cab1 18%, transparent)",
  "--glass-diff-deletion-bg": "color-mix(in srgb, #ff2e3f 18%, transparent)",
};

export const PIERRE_LIGHT_VARS: Record<string, string> = {
  "--foreground": "#070707",
  "--primary": "#009fff",
  "--primary-foreground": "#ffffff",
  "--secondary": "color-mix(in srgb, #070707 4%, #ffffff)",
  "--secondary-foreground": "#070707",
  "--muted": "color-mix(in srgb, #070707 4%, #ffffff)",
  "--muted-foreground": "#6c6c71",
  "--accent": "#dfebff73",
  "--accent-foreground": "#070707",
  "--destructive": "#ff2e3f",
  "--border": "#eeeeef",
  "--input": "#dbdbdd",
  "--ring": "oklch(0.68 0.14 245 / 38%)",
  "--glass-color-sidebar": "#f8f8f8",
  "--glass-color-chat": "#fafafa",
  "--glass-color-editor": "#ffffff",
  "--glass-color-surface": "#f5f5f6",
  "--glass-color-elevated": "#eeeeef",
  "--glass-color-bubble": "color-mix(in srgb, #eeeeef 88%, transparent)",
  "--glass-color-bubble-opaque": "#eeeeef",
  "--glass-color-menubar": "color-mix(in srgb, #ffffff 82%, #f8f8f8)",
  "--glass-color-border": "color-mix(in srgb, #070707 10%, transparent)",
  "--glass-color-stroke": "color-mix(in srgb, #070707 8%, transparent)",
  "--glass-color-stroke-tertiary": "color-mix(in srgb, #070707 6%, transparent)",
  "--glass-color-stroke-strong": "color-mix(in srgb, #070707 12%, transparent)",
  "--glass-color-hover": "#dfebff59",
  "--glass-color-active": "#dfebffcc",
  "--glass-diff-addition": "#00cab1",
  "--glass-diff-deletion": "#ff2e3f",
  "--glass-diff-addition-bg": "color-mix(in srgb, #00cab1 15%, transparent)",
  "--glass-diff-deletion-bg": "color-mix(in srgb, #ff2e3f 15%, transparent)",
};

export const ALL_PRESET_VAR_KEYS = [
  ...new Set([...Object.keys(PIERRE_DARK_VARS), ...Object.keys(PIERRE_LIGHT_VARS)]),
];
